name: Build and release

on:
  push:
    branches: 
      - 'main'
      - 'master'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Clients - SimpleWeb
      - run: |
          cd ./Clients/SimpleWeb/web;
          npm ci;
          npm run build;
          cd ./dist;
          cp ../../../../License/* ./;
          tar -czvf SimpleWeb.tar.gz ./*;

      # Clients - Node-RED
      - run: |
          cd ./Clients/Node-RED;
          node build.js;
          mkdir dist;
          cd dist;
          cp ../../../License/* ./;
          tar -czvf SimpleWeb-NodeRED.tar.gz ../*.json;

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "SimpleWeb Client"
          files: |
            Clients/SimpleWeb/web/dist/*.tar.gz

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "SimpleWeb Node-RED Client"
          files: |
            Clients/Node-RED/dist/*.tar.gz