name: Build and release

on:
  push:
    branches: 
      - 'main'
      - 'master'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Clients - SimpleWeb
      - run: |
          cd ./Clients/SimpleWeb/web;
          npm ci;
          npm run build;

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "SimpleWeb Client"
          files: |
            License/*
            Clients/SimpleWeb/web/dist/*